language: python

python:
        - "3.5"

before_install:
        - sudo apt-get install python3-tk

install:
        - pip install matplotlib flake8 pytest
        - pip install -r requirements.txt

script:
        - flake8 .
        - python -m pytest tests